### ISSUE TITLE
Safari 6 desktop

### ISSUE THREAD

**Issue by mattcph** [crowdfavorite/css-grid#2]
Horizontal scroll appears right before media response kicks in... thanks.

**Comment by alexkingorg** [comment]
Which branch is this in? We are currently putting most of our efforts into e feature/twelve-column branch.

**Comment by mattcph** [comment]
Feature 12-col. for my safari 6, thanks

**Comment by devinreams** [comment]
We committed a fix at 0f81510e2a5fb5c36c28798bb7b62f3d818f9f55 which tweaks the breakpoints so that the grid changes before the screen gets too small (for both large > medium and xtra-large > large). 

We confirmed this should accommodate the margin and confirmed the breakpoints work fine with no x-axis overflow by opening the example.html page and resizing the window...
